name: Tacticalcontact
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66394
title: Tactical marketing platforms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2984ba'
    - '#54a5d4'
    - '#f17e00'
    - '#c4c4c4'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.679909503320232
  rhythmicContrast: 0.5
purpose: []
